_target_: envs.factory.make_env

id: SwingUp-v0
# id: CartPole-v1
entry_point: envs.swing_up:SwingUpEnv
# entry_point: Null
num_envs: 8
seed: Null 
render_mode: rgb_array
wrappers:
  - _target_: gymnasium.wrappers.vector.RecordEpisodeStatistics
    _partial_: True